require('dotenv').config()
const express = require('express')
const {corsOptions} = require('./config/corsOptions')
const cors = require('cors')
const app = express()
const credentials = require('./middleware/credentials')
const mongoose = require('mongoose')
const {connectionDB} = require('./database/planDB')
const addUserPlan = require('./router/planRoute')
const addProducto = require('./router/productosRoute')
const getProductos = require('./router/productosRoute')
const addUser = require('./router/userRoute')
const getAllUsers = require('./router/userRoute')
const addClase = require('./router/claseRoute')

app.use(credentials)
app.use(cors(corsOptions))
app.use(express.json())

//declaro app.(metodo)(ruta,funcion)
app.use('/',addUserPlan)
app.use('/',addProducto)
app.use('/',getProductos)
app.use('/',addUser)
app.use('/',getAllUsers)
app.use('/',addClase)

app.listen(process.env.PORT,()=> console.log(`escuchando en el puerto ${process.env.PORT}`))