require('dotenv').config()
const express = require('express')
const {corsOptions} = require('./config/corsOptions')
const cors = require('cors')
const app = express()
const credentials = require('./middleware/credentials')
const mongoose = require('mongoose')
const {connectionDB} = require('./database/planDB')
const addUserPlan = require('./router/planRoute')
const addProducto = require('./router/productosRoute')
const getProductos = require('./router/productosRoute')
const addUser = require('./router/userRoute')
const getAllUsers = require('./router/userRoute')
const addClase = require('./router/claseRoute')
const loginUser = require('./router/authRoute')
const refreshToken = require('./router/refreshRoute')
const handleLogout = require('./router/logoutRoute')
const cookieParser = require('cookie-parser')

app.use(credentials)
app.use(cors(corsOptions))
app.use(express.json())
app.use(cookieParser())
//declaro app.(metodo)(ruta,funcion)

app.use('/',addUserPlan)
app.use('/',addProducto)
app.use('/',getProductos)
app.use('/',addUser)
app.use('/',getAllUsers)
app.use('/',addClase)
app.use('/',loginUser)
app.use('/',refreshToken)
app.use('/',handleLogout)
app.listen(process.env.PORT,()=> console.log(`escuchando en el puerto ${process.env.PORT}`))